### ISSUE TITLE
Pantheon not showing accounts.

### ISSUE THREAD

**Issue by Genysys** [brave-experiments/Mjolnir#196]
There is an issue with pantheon where it fails to show accounts:
i.e.

```
>web3.eth.accounts
[]
```

**Comment by drandreaskrueger** [comment]
"This method returns an empty object because Besu doesn’t support key management inside the client. Use EthSigner with Besu to provide access to your key store and sign transactions."

https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_accounts
